### ISSUE TITLE
Archlinux, Python 2.7.13, error about UnicodeEncodeError and TypeError

### ISSUE THREAD

**Issue by vcinex** [creatorYC/v2ex-terminal#1]
```
Traceback (most recent call last):
  File "v2ex.py", line 92, in <module>
    main()
  File "v2ex.py", line 60, in main
    resp = login()
  File "~/v2ex-terminal/login.py", line 100, in login
    username = raw_input(termcolor.colored(u'输入用户名: ', 'cyan'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)
```
For this one, I just turn 

```
username = raw_input(termcolor.colored(u'输入用户名: ', 'cyan'))
password = raw_input(termcolor.colored(u'输入密码: ', 'cyan'))
```
into
```
username = raw_input(termcolor.colored('输入用户名: ', 'cyan'))
password = raw_input(termcolor.colored('输入密码: ', 'cyan'))
```
and it worked.

```
Traceback (most recent call last):
  File "v2ex.py", line 92, in <module>
    main()
  File "v2ex.py", line 73, in main
    work()
  File "~/v2ex-terminal/operate.py", line 188, in work
    welcome()
  File "~/v2ex-terminal/operate.py", line 144, in welcome
    get_my_time()
  File "~/v2ex-terminal/operate.py", line 100, in get_my_time
    url = home_page_url + "/api/members/show.json?username=" + globlevalue.username
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
For this one, I turn `url = home_page_url + "/api/members/show.json?username=" + globlevalue.username` into `url = str(home_page_url) + "/api/members/show.json?username=" + str(globlevalue.username)` and it worked.

Besides, the order `clear` didn't work.

**Comment by ye-yechen** [comment]
我是在windows下开发的，使用的是 cmder 终端，clear() 使用的是windows的“cls”命令，在linux下应该是“clear”吧。另外这个编码问题真是很醉...
